---
deployment:
  tasks:
    - export DEPLOYPATH=/home/goopizco/sandbox/frontend/
    #- /bin cp * $DEPLOYPATH
    #- /bin/cp -r * $DEPLOYPATH
    - /bin/rsync -Paz --exclude="database.php" * $DEPLOYPATH